<?php
/**
 * Country Blocker - Status Dashboard
 * 
 * Author: Silvester van der Leer (svdleer)
 * Repository: https://github.com/svdleer/countryblocker
 * License: MIT
 * 
 * SECURITY NOTES:
 * - This page is READ-ONLY, no write operations
 * - Requires basic authentication (configure in .htaccess)
 * - No user input processing
 * - Data is loaded from JSON file generated by system
 */

// Configuration
// Try local stats.json first (for Plesk/open_basedir restrictions), then fallback to system location
$stats_files = [
    __DIR__ . '/stats.json',           // Local copy (Plesk-friendly)
    '/var/lib/ipdeny/stats.json'       // System location
];
define('REFRESH_INTERVAL', 60); // seconds

// Security: Read-only mode
header('X-Content-Type-Options: nosniff');
header('X-Frame-Options: DENY');
header('X-XSS-Protection: 1; mode=block');

// Load statistics from first available file
$stats = [];
$stats_file_used = null;
foreach ($stats_files as $file) {
    if (@file_exists($file) && is_readable($file)) {
        $stats = json_decode(file_get_contents($file), true) ?? [];
        $stats_file_used = $file;
        break;
    }
}

$last_updated = isset($stats['timestamp']) ? date('Y-m-d H:i:s', $stats['timestamp']) : 'Never';
$ipsets = $stats['ipsets'] ?? [];
$summary = $stats['summary'] ?? [];
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="refresh" content="<?= REFRESH_INTERVAL ?>">
    <title>Country Blocker - Status Dashboard</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            padding: 20px;
            color: #333;
        }
        
        .container {
            max-width: 1200px;
            margin: 0 auto;
        }
        
        .header {
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            margin-bottom: 20px;
        }
        
        .header h1 {
            color: #667eea;
            margin-bottom: 10px;
        }
        
        .header .subtitle {
            color: #666;
            font-size: 14px;
        }
        
        .header .last-updated {
            margin-top: 15px;
            padding: 10px;
            background: #f0f0f0;
            border-radius: 5px;
            font-size: 14px;
        }
        
        .summary-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin-bottom: 20px;
        }
        
        .summary-card {
            background: white;
            padding: 25px;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            text-align: center;
        }
        
        .summary-card .label {
            font-size: 14px;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 1px;
            margin-bottom: 10px;
        }
        
        .summary-card .value {
            font-size: 36px;
            font-weight: bold;
            color: #667eea;
        }
        
        .summary-card .subvalue {
            font-size: 14px;
            color: #999;
            margin-top: 5px;
        }
        
        .ipsets-table {
            background: white;
            padding: 30px;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            overflow-x: auto;
        }
        
        .ipsets-table h2 {
            color: #667eea;
            margin-bottom: 20px;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
        }
        
        th {
            background: #f8f9fa;
            padding: 12px;
            text-align: left;
            font-weight: 600;
            color: #333;
            border-bottom: 2px solid #dee2e6;
        }
        
        td {
            padding: 12px;
            border-bottom: 1px solid #dee2e6;
        }
        
        tr:hover {
            background: #f8f9fa;
        }
        
        .country-code {
            font-weight: bold;
            color: #667eea;
        }
        
        .badge {
            display: inline-block;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 12px;
            font-weight: 600;
        }
        
        .badge-v4 {
            background: #e3f2fd;
            color: #1976d2;
        }
        
        .badge-v6 {
            background: #f3e5f5;
            color: #7b1fa2;
        }
        
        .number {
            font-family: 'Courier New', monospace;
            font-weight: 600;
        }
        
        .footer {
            text-align: center;
            color: white;
            margin-top: 30px;
            font-size: 14px;
        }
        
        .footer a {
            color: white;
            text-decoration: underline;
        }
        
        .status-indicator {
            display: inline-block;
            width: 10px;
            height: 10px;
            border-radius: 50%;
            margin-right: 8px;
        }
        
        .status-active {
            background: #4caf50;
            box-shadow: 0 0 10px #4caf50;
        }
        
        .status-inactive {
            background: #f44336;
        }
        
        @media (max-width: 768px) {
            .summary-grid {
                grid-template-columns: 1fr;
            }
            
            table {
                font-size: 14px;
            }
            
            th, td {
                padding: 8px;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🛡️ Country Blocker Status</h1>
            <p class="subtitle">Automated IP blocklist management with systemd, ipset, and iptables</p>
            <div class="last-updated">
                <span class="status-indicator status-active"></span>
                <strong>Last Updated:</strong> <?= htmlspecialchars($last_updated) ?>
                <span style="float: right;">Auto-refresh: <?= REFRESH_INTERVAL ?>s</span>
            </div>
        </div>
        
        <?php if (!empty($summary)): ?>
        <div class="summary-grid">
            <div class="summary-card">
                <div class="label">Total Countries</div>
                <div class="value"><?= number_format($summary['total_countries'] ?? 0) ?></div>
            </div>
            
            <div class="summary-card">
                <div class="label">IP Entries</div>
                <div class="value"><?= number_format($summary['total_entries'] ?? 0) ?></div>
                <div class="subvalue">IPv4: <?= number_format($summary['ipv4_sets'] ?? 0) ?> | IPv6: <?= number_format($summary['ipv6_sets'] ?? 0) ?></div>
            </div>
            
            <div class="summary-card">
                <div class="label">Blocked Packets</div>
                <div class="value"><?= number_format($summary['total_packets'] ?? 0) ?></div>
            </div>
            
            <div class="summary-card">
                <div class="label">Blocked Traffic</div>
                <div class="value"><?= htmlspecialchars($summary['total_traffic'] ?? '0B') ?></div>
            </div>
        </div>
        <?php endif; ?>
        
        <div class="ipsets-table">
            <h2>📊 Active IPsets</h2>
            
            <?php if (empty($ipsets)): ?>
                <p style="text-align: center; color: #999; padding: 40px;">
                    No statistics available. Run <code>ipdeny-ctl update-web</code> to generate data.
                </p>
            <?php else: ?>
                <table>
                    <thead>
                        <tr>
                            <th>Country</th>
                            <th>Type</th>
                            <th>Entries</th>
                            <th>Memory</th>
                            <th>Packets Blocked</th>
                            <th>Traffic Blocked</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($ipsets as $ipset): ?>
                        <tr>
                            <td><span class="country-code"><?= strtoupper(htmlspecialchars($ipset['country'] ?? '')) ?></span></td>
                            <td>
                                <span class="badge <?= $ipset['type'] === 'v4' ? 'badge-v4' : 'badge-v6' ?>">
                                    IPv<?= htmlspecialchars($ipset['type'] ?? '') ?>
                                </span>
                            </td>
                            <td class="number"><?= number_format($ipset['entries'] ?? 0) ?></td>
                            <td class="number"><?= htmlspecialchars($ipset['memory'] ?? 'N/A') ?></td>
                            <td class="number"><?= number_format($ipset['packets'] ?? 0) ?></td>
                            <td class="number"><?= htmlspecialchars($ipset['traffic'] ?? '0B') ?></td>
                        </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            <?php endif; ?>
        </div>
        
        <div class="footer">
            <p>
                <strong>Country Blocker</strong> by 
                <a href="https://github.com/svdleer" target="_blank">Silvester van der Leer</a>
                | 
                <a href="https://github.com/svdleer/countryblocker" target="_blank">GitHub Repository</a>
            </p>
        </div>
    </div>
</body>
</html>
